[locale]
fiat = "aud"
fy_start_month = 7

[logging]
level = "INFO"
format = "%(asctime)s - %(levelname)s - %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[options]
position_accounting = "filo"
sort_by_datetime_asc = true
precision_threshold = 0.00000001

[data]
fiats = ["usd", "aud"]
cryptos = ["btc", "ltc", "nmc", "eth", "bch", "link"]
operations = ["buy", "sell", "deposit", "withdrawal", "loss"]
parse_datetime_formats = ["%m/%d/%Y %H:%M:%S", "%b. %d, %Y, %I:%M %p", "%b. %d, %Y, %H:%M %p", "%Y-%m-%d %H:%M:%S"]

[data.fields]
"Type" = "_type"
"Exchange" = "exchange"
"Datetime" = "datetime"
"Operation" = "operation"
"Pair" = "pair"
"Comments" = "comments"

[data.pair_split_map]
btcusd = ["btc", "usd"]
btcaud = ["btc", "aud"]
ltcusd = ["ltc", "usd"]
nmcusd = ["nmc", "usd"]
xethxxbt = ["eth", "btc"]
xethzusd = ["eth", "usd"]
ethusd = ["eth", "usd"]
xltczusd = ["ltc", "usd"]
xxbtzusd = ["btc", "usd"]
xltcxxbt = ["ltc", "btc"]
bchusd = ["bch", "usd"]
linkusd = ["link", "usd"]
linkaud = ["link", "aud"]